// <auto-generated />
using System;
using Kont.backend.DAL.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kont.backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20250915101734_Add IsActive field on administrator")]
    partial class AddIsActivefieldonadministrator
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AdministratorSite", b =>
                {
                    b.Property<Guid>("AdministratorsId")
                        .HasColumnType("uuid")
                        .HasColumnName("administrators_id");

                    b.Property<Guid>("SitesId")
                        .HasColumnType("uuid")
                        .HasColumnName("sites_id");

                    b.HasKey("AdministratorsId", "SitesId")
                        .HasName("pk_administrator_site");

                    b.HasIndex("SitesId")
                        .HasDatabaseName("ix_administrator_site_sites_id");

                    b.ToTable("administrator_site", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Activity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.HasKey("Id")
                        .HasName("pk_activity");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_activity_created_by_id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_activity_event_id");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_activity_site_id");

                    b.ToTable("activity", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.ActivitySummaryData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_entity_id");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision")
                        .HasColumnName("average_score");

                    b.Property<double>("BestScore")
                        .HasColumnType("double precision")
                        .HasColumnName("best_score");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<int>("PlayersPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("players_played");

                    b.Property<Guid>("PoolEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_entity_id");

                    b.HasKey("Id")
                        .HasName("pk_activity_summary_data");

                    b.HasIndex("ActivityEntityId")
                        .HasDatabaseName("ix_activity_summary_data_activity_entity_id");

                    b.HasIndex("PoolEntityId")
                        .HasDatabaseName("ix_activity_summary_data_pool_entity_id");

                    b.ToTable("activity_summary_data", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<Guid?>("ManagerId")
                        .HasColumnType("uuid")
                        .HasColumnName("manager_id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<Guid>("SubscriptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("subscription_id");

                    b.HasKey("Id")
                        .HasName("pk_administrator");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_administrator_email");

                    b.HasIndex("ManagerId")
                        .HasDatabaseName("ix_administrator_manager_id");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_administrator_role_id");

                    b.HasIndex("SubscriptionId")
                        .HasDatabaseName("ix_administrator_subscription_id");

                    b.ToTable("administrator", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<string>("EventLink")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_link");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<DateTime?>("StartedAt")
                        .IsRequired()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_event");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_event_site_id");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.GameSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_game_session");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_game_session_activity_id");

                    b.HasIndex("PoolId")
                        .HasDatabaseName("ix_game_session_pool_id");

                    b.ToTable("game_session", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.GroupScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<double>("AverageScore")
                        .HasColumnType("double precision")
                        .HasColumnName("average_score");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("group_id");

                    b.Property<int>("PlayerCount")
                        .HasColumnType("integer")
                        .HasColumnName("player_count");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_group_score");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_group_score_activity_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_group_score_group_id");

                    b.ToTable("group_score", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("firstname");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lastname");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("password");

                    b.Property<string>("PlayerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_type");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_player_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_player_username");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerActivityScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_entity_id");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<Guid>("PlayerEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_entity_id");

                    b.Property<Guid>("PoolEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_entity_id");

                    b.Property<int>("Rank")
                        .HasColumnType("integer")
                        .HasColumnName("rank");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_player_activity_score");

                    b.HasIndex("ActivityEntityId")
                        .HasDatabaseName("ix_player_activity_score_activity_entity_id");

                    b.HasIndex("PlayerEntityId")
                        .HasDatabaseName("ix_player_activity_score_player_entity_id");

                    b.HasIndex("PoolEntityId")
                        .HasDatabaseName("ix_player_activity_score_pool_entity_id");

                    b.ToTable("player_activity_score", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerGlobalScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ActivitiesPlayed")
                        .HasColumnType("integer")
                        .HasColumnName("activities_played");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("calculated_at");

                    b.Property<int>("GlobalRank")
                        .HasColumnType("integer")
                        .HasColumnName("global_rank");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_updated_at");

                    b.Property<double>("Percentage")
                        .HasColumnType("double precision")
                        .HasColumnName("percentage");

                    b.Property<Guid>("PlayerEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_entity_id");

                    b.Property<Guid>("PoolEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_entity_id");

                    b.Property<double>("TotalScore")
                        .HasColumnType("double precision")
                        .HasColumnName("total_score");

                    b.HasKey("Id")
                        .HasName("pk_player_global_score");

                    b.HasIndex("PlayerEntityId")
                        .HasDatabaseName("ix_player_global_score_player_entity_id");

                    b.HasIndex("PoolEntityId")
                        .HasDatabaseName("ix_player_global_score_pool_entity_id");

                    b.ToTable("player_global_score", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("GameSessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_session_id");

                    b.Property<int>("GroupNumber")
                        .HasColumnType("integer")
                        .HasColumnName("group_number");

                    b.HasKey("Id")
                        .HasName("pk_player_group");

                    b.HasIndex("GameSessionId")
                        .HasDatabaseName("ix_player_group_game_session_id");

                    b.ToTable("player_group", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerRegistration", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("checked_in_at");

                    b.Property<Guid?>("PlayerGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_group_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("PoolId")
                        .HasColumnType("uuid")
                        .HasColumnName("pool_id");

                    b.Property<DateTime>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.HasKey("Id")
                        .HasName("pk_player_registration");

                    b.HasIndex("PlayerGroupId")
                        .HasDatabaseName("ix_player_registration_player_group_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_registration_player_id");

                    b.HasIndex("PoolId")
                        .HasDatabaseName("ix_player_registration_pool_id");

                    b.ToTable("player_registration", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<Guid>("ScoringMetricId")
                        .HasColumnType("uuid")
                        .HasColumnName("scoring_metric_id");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_player_score");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_player_score_activity_id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_player_score_player_id");

                    b.HasIndex("ScoringMetricId")
                        .HasDatabaseName("ix_player_score_scoring_metric_id");

                    b.ToTable("player_score", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Pool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ended_at");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsAllPlayersPresent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_all_players_present");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("qr_code");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_pool");

                    b.HasIndex("EventId")
                        .HasDatabaseName("ix_pool_event_id");

                    b.ToTable("pool", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("RoleType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_type");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.ScoringMetric", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid")
                        .HasColumnName("activity_id");

                    b.Property<double>("Coefficient")
                        .HasColumnType("double precision")
                        .HasColumnName("coefficient");

                    b.Property<bool>("HigherIsBetter")
                        .HasColumnType("boolean")
                        .HasColumnName("higher_is_better");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("unit");

                    b.HasKey("Id")
                        .HasName("pk_scoring_metric");

                    b.HasIndex("ActivityId")
                        .HasDatabaseName("ix_scoring_metric_activity_id");

                    b.ToTable("scoring_metric", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Site", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("address");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("city");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Logo")
                        .HasColumnType("text")
                        .HasColumnName("logo");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("phone_number");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("state");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("zip_code");

                    b.HasKey("Id")
                        .HasName("pk_site");

                    b.ToTable("site", (string)null);
                });

            modelBuilder.Entity("Kont.backend.DAL.Subscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("SubscriptionType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscription_type");

                    b.HasKey("Id")
                        .HasName("pk_subscription");

                    b.ToTable("subscription", (string)null);
                });

            modelBuilder.Entity("AdministratorSite", b =>
                {
                    b.HasOne("Kont.backend.DAL.Administrator", null)
                        .WithMany()
                        .HasForeignKey("AdministratorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_site_administrator_administrators_id");

                    b.HasOne("Kont.backend.DAL.Site", null)
                        .WithMany()
                        .HasForeignKey("SitesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_site_site_sites_id");
                });

            modelBuilder.Entity("Kont.backend.DAL.Activity", b =>
                {
                    b.HasOne("Kont.backend.DAL.Administrator", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_administrator_created_by_id");

                    b.HasOne("Kont.backend.DAL.Event", null)
                        .WithMany("Activities")
                        .HasForeignKey("EventId")
                        .HasConstraintName("fk_activity_event_event_id");

                    b.HasOne("Kont.backend.DAL.Site", "Site")
                        .WithMany("Activities")
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_site_site_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Kont.backend.DAL.ActivitySummaryData", b =>
                {
                    b.HasOne("Kont.backend.DAL.Activity", "ActivityEntity")
                        .WithMany()
                        .HasForeignKey("ActivityEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_summary_data_activity_activity_entity_id");

                    b.HasOne("Kont.backend.DAL.Pool", "PoolEntity")
                        .WithMany()
                        .HasForeignKey("PoolEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_activity_summary_data_pool_pool_entity_id");

                    b.Navigation("ActivityEntity");

                    b.Navigation("PoolEntity");
                });

            modelBuilder.Entity("Kont.backend.DAL.Administrator", b =>
                {
                    b.HasOne("Kont.backend.DAL.Administrator", "Manager")
                        .WithMany()
                        .HasForeignKey("ManagerId")
                        .HasConstraintName("fk_administrator_administrator_manager_id");

                    b.HasOne("Kont.backend.DAL.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_role_role_id");

                    b.HasOne("Kont.backend.DAL.Subscription", "Subscription")
                        .WithMany()
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_administrator_subscription_subscription_id");

                    b.Navigation("Manager");

                    b.Navigation("Role");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("Kont.backend.DAL.Event", b =>
                {
                    b.HasOne("Kont.backend.DAL.Site", "Site")
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_site_site_id");

                    b.Navigation("Site");
                });

            modelBuilder.Entity("Kont.backend.DAL.GameSession", b =>
                {
                    b.HasOne("Kont.backend.DAL.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_activity_activity_id");

                    b.HasOne("Kont.backend.DAL.Pool", "Pool")
                        .WithMany("GameSessions")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_game_session_pool_pool_id");

                    b.Navigation("Activity");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("Kont.backend.DAL.GroupScore", b =>
                {
                    b.HasOne("Kont.backend.DAL.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_score_activity_activity_id");

                    b.HasOne("Kont.backend.DAL.PlayerGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_group_score_player_group_group_id");

                    b.Navigation("Activity");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerActivityScore", b =>
                {
                    b.HasOne("Kont.backend.DAL.Activity", "ActivityEntity")
                        .WithMany()
                        .HasForeignKey("ActivityEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_activity_score_activity_activity_entity_id");

                    b.HasOne("Kont.backend.DAL.Player", "PlayerEntity")
                        .WithMany()
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_activity_score_player_player_entity_id");

                    b.HasOne("Kont.backend.DAL.Pool", "PoolEntity")
                        .WithMany()
                        .HasForeignKey("PoolEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_activity_score_pool_pool_entity_id");

                    b.Navigation("ActivityEntity");

                    b.Navigation("PlayerEntity");

                    b.Navigation("PoolEntity");
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerGlobalScore", b =>
                {
                    b.HasOne("Kont.backend.DAL.Player", "PlayerEntity")
                        .WithMany()
                        .HasForeignKey("PlayerEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_global_score_player_player_entity_id");

                    b.HasOne("Kont.backend.DAL.Pool", "PoolEntity")
                        .WithMany()
                        .HasForeignKey("PoolEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_global_score_pool_pool_entity_id");

                    b.Navigation("PlayerEntity");

                    b.Navigation("PoolEntity");
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerGroup", b =>
                {
                    b.HasOne("Kont.backend.DAL.GameSession", "GameSession")
                        .WithMany("PlayerGroups")
                        .HasForeignKey("GameSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_group_game_session_game_session_id");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerRegistration", b =>
                {
                    b.HasOne("Kont.backend.DAL.PlayerGroup", null)
                        .WithMany("Players")
                        .HasForeignKey("PlayerGroupId")
                        .HasConstraintName("fk_player_registration_player_group_player_group_id");

                    b.HasOne("Kont.backend.DAL.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_registration_player_player_id");

                    b.HasOne("Kont.backend.DAL.Pool", "Pool")
                        .WithMany("PlayerRegistrations")
                        .HasForeignKey("PoolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_registration_pool_pool_id");

                    b.Navigation("Player");

                    b.Navigation("Pool");
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerScore", b =>
                {
                    b.HasOne("Kont.backend.DAL.Activity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_score_activity_activity_id");

                    b.HasOne("Kont.backend.DAL.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_score_player_player_id");

                    b.HasOne("Kont.backend.DAL.ScoringMetric", "ScoringMetric")
                        .WithMany()
                        .HasForeignKey("ScoringMetricId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_player_score_scoring_metric_scoring_metric_id");

                    b.Navigation("Activity");

                    b.Navigation("Player");

                    b.Navigation("ScoringMetric");
                });

            modelBuilder.Entity("Kont.backend.DAL.Pool", b =>
                {
                    b.HasOne("Kont.backend.DAL.Event", "Event")
                        .WithMany("Pools")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pool_event_event_id");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Kont.backend.DAL.ScoringMetric", b =>
                {
                    b.HasOne("Kont.backend.DAL.Activity", "Activity")
                        .WithMany("ScoringMetrics")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_scoring_metric_activity_activity_id");

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Kont.backend.DAL.Activity", b =>
                {
                    b.Navigation("ScoringMetrics");
                });

            modelBuilder.Entity("Kont.backend.DAL.Event", b =>
                {
                    b.Navigation("Activities");

                    b.Navigation("Pools");
                });

            modelBuilder.Entity("Kont.backend.DAL.GameSession", b =>
                {
                    b.Navigation("PlayerGroups");
                });

            modelBuilder.Entity("Kont.backend.DAL.PlayerGroup", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Kont.backend.DAL.Pool", b =>
                {
                    b.Navigation("GameSessions");

                    b.Navigation("PlayerRegistrations");
                });

            modelBuilder.Entity("Kont.backend.DAL.Site", b =>
                {
                    b.Navigation("Activities");
                });
#pragma warning restore 612, 618
        }
    }
}
